#!/usr/bin/env python3
"""Generate the face's watch face editor configuration.

The wearer customises the face in the watch's own editor (Watch Face menu, Customise):
which complication each ring segment shows, a colour scheme (the editor's Style),
the colour for the Single colour scheme (Data colour), and the colour of the time,
date and weather (Accent colour). Everything is listed once here and written out to:

    resources/configs/watchface.xml   the editor's slots, styles and colour lists
    resources/strings/choices.xml     names for the styles and colours
    source/Choices.mc                 the same lists for the face

    python3 tools/make_settings.py
"""
import os

# Complication types a segment can show, as (Complications constant, type number,
# Icons constant). Only types with a natural 'full' are offered; the face computes
# each fraction in DataSources.forData. Sunset stands for Daylight left, which
# drains from sunrise to sunset.
DATA = [
    ('COMPLICATION_TYPE_BATTERY', 1, 'BATTERY'),
    ('COMPLICATION_TYPE_HEART_RATE', 18, 'HEART'),
    ('COMPLICATION_TYPE_STEPS', 2, 'FOOTPRINTS'),
    ('COMPLICATION_TYPE_SOLAR_INPUT', 37, 'SUN'),
    ('COMPLICATION_TYPE_BODY_BATTERY', 23, 'BOLT'),
    ('COMPLICATION_TYPE_RECOVERY_TIME', 21, 'GAUGE'),
    ('COMPLICATION_TYPE_STRESS', 22, 'STRESS'),
    ('COMPLICATION_TYPE_FLOORS_CLIMBED', 4, 'STAIRS'),
    ('COMPLICATION_TYPE_INTENSITY_MINUTES', 5, 'STOPWATCH'),
    ('COMPLICATION_TYPE_PULSE_OX', 35, 'DROP'),
    ('COMPLICATION_TYPE_SLEEP_SCORE', 42, 'MOON'),
    ('COMPLICATION_TYPE_SUNSET', 14, 'SUNRISE'),
]

# The six segments' default complications, clockwise from the top.
DEFAULT_DATA = ['COMPLICATION_TYPE_BATTERY', 'COMPLICATION_TYPE_HEART_RATE', 'COMPLICATION_TYPE_STEPS',
                'COMPLICATION_TYPE_SOLAR_INPUT', 'COMPLICATION_TYPE_BODY_BATTERY',
                'COMPLICATION_TYPE_RECOVERY_TIME']

# Colour schemes, offered as the editor's styles: (id, name, six colours clockwise
# from the top). A scheme of None uses the Data colour for every segment. Style ids
# are stored in the wearer's settings, so never renumber them.
SCHEMES = [
    (1, 'Rainbow', [0x00FF55, 0xFF0055, 0x00AAFF, 0xFFAA00, 0xAA55FF, 0xFFFF00]),
    (2, 'Warm', [0xFFFF00, 0xFFAA00, 0xFF5500, 0xFF0000, 0xFF0055, 0xFF55AA]),
    (3, 'Cool', [0x00FFFF, 0x00AAFF, 0x0055FF, 0x5555FF, 0xAA55FF, 0x00FFAA]),
    (4, 'Pastel', [0xAAFFAA, 0xFFAAAA, 0xAAFFFF, 0xFFFFAA, 0xFFAAFF, 0xAAAAFF]),
    (5, 'Single colour', None),
]
DEFAULT_SCHEME = 1
DEFAULT_DATA_COLOUR = 0x00FF55
DEFAULT_ACCENT_COLOUR = 0xFFFFFF

# Every colour the 64-colour display shows except black, which would hide the dots
# and text. Keyed by each channel's level: 0, 1, 2, 3 for 00, 55, AA, FF.
COLOUR_NAMES = {
    '001': 'Navy', '002': 'Dark blue', '003': 'Blue',
    '010': 'Dark green', '011': 'Dark teal', '012': 'Sapphire', '013': 'Royal blue',
    '020': 'Green', '021': 'Sea green', '022': 'Teal', '023': 'Sky blue',
    '030': 'Bright green', '031': 'Spring green', '032': 'Aquamarine', '033': 'Cyan',
    '100': 'Maroon', '101': 'Plum', '102': 'Indigo', '103': 'Electric indigo',
    '110': 'Olive', '111': 'Dark grey', '112': 'Slate blue', '113': 'Periwinkle',
    '120': 'Leaf green', '121': 'Moss', '122': 'Cadet blue', '123': 'Cornflower blue',
    '130': 'Chartreuse', '131': 'Light green', '132': 'Mint', '133': 'Light cyan',
    '200': 'Dark red', '201': 'Burgundy', '202': 'Purple', '203': 'Violet',
    '210': 'Brown', '211': 'Dusty red', '212': 'Mauve', '213': 'Amethyst',
    '220': 'Dark yellow', '221': 'Khaki', '222': 'Light grey', '223': 'Lavender blue',
    '230': 'Yellow green', '231': 'Light lime', '232': 'Pale green', '233': 'Pale cyan',
    '300': 'Red', '301': 'Crimson', '302': 'Hot pink', '303': 'Magenta',
    '310': 'Red orange', '311': 'Coral', '312': 'Pink', '313': 'Light magenta',
    '320': 'Orange', '321': 'Apricot', '322': 'Salmon', '323': 'Light orchid',
    '330': 'Yellow', '331': 'Lemon', '332': 'Pale yellow', '333': 'White',
}


def colours():
    return [(sum(int(level) * 0x55 << shift for level, shift in zip(key, (16, 8, 0))), name)
            for key, name in COLOUR_NAMES.items()]


def string_id(name):
    return ''.join(w[:1].upper() + w[1:] for w in name.replace('-', ' ').split())


CHOICES = """// Generated by tools/make_settings.py: edit the lists there, then regenerate.
import Toybox.Complications;
import Toybox.Lang;

// What the watch face editor offers, and the defaults for anything not yet chosen.
module Choices {{

    // Icons number for each complication type a segment can show, indexed by type;
    // -1 for types that are not offered.
    const ICONS = [{icons}] as Array<Number>;

    // Each segment's default complication type, clockwise from the top.
    const DEFAULT_DATA = [
{default_data}
    ] as Array<Number>;

    // Colour schemes by style id: six colours clockwise from the top, or null for
    // Single colour, which uses the Data colour throughout.
    const SCHEMES = [
{schemes}
    ] as Array<Array<Number>?>;

    const DEFAULT_SCHEME = {default_scheme};
    const DEFAULT_DATA_COLOUR = 0x{default_data_colour:06X};
    const DEFAULT_ACCENT_COLOUR = 0x{default_accent_colour:06X};
}}
"""


def main():
    root = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..')
    cols = colours()
    names = [n for _, n in cols]
    rgbs = [c for c, _ in cols]
    assert len(set(names)) == len(names), 'colour names must be unique'
    assert DEFAULT_DATA_COLOUR in rgbs and DEFAULT_ACCENT_COLOUR in rgbs
    assert all(c in rgbs for _, _, cs in SCHEMES if cs for c in cs), 'scheme colours must be in the list'
    assert all(len(cs) == len(DEFAULT_DATA) for _, _, cs in SCHEMES if cs)
    assert [s[0] for s in SCHEMES] == list(range(1, len(SCHEMES) + 1)), 'style ids must run 1, 2, 3, ...'
    types = {const: number for const, number, _ in DATA}

    strings = ['<strings>', '    <!-- Generated by tools/make_settings.py -->']
    for _, name, _ in SCHEMES:
        strings.append('    <string id="Style%s">%s</string>' % (string_id(name), name))
    for _, name in cols:
        strings.append('    <string id="Colour%s">%s</string>' % (string_id(name), name))
    strings.append('</strings>')

    def colour_list(tag, default):
        out = ['        <%s>' % tag]
        for rgb, name in cols:
            out.append('            <color label="@Strings.Colour%s"%s>0x%06X</color>'
                       % (string_id(name), ' default="true"' if rgb == default else '', rgb))
        out.append('        </%s>' % tag)
        return out

    config = ['<resources>', '    <!-- Generated by tools/make_settings.py -->', '    <watchface-config>',
              '        <styles>']
    for id_, name, _ in SCHEMES:
        config.append('            <style id="%d" label="@Strings.Style%s"%s/>'
                      % (id_, string_id(name), ' default="true"' if id_ == DEFAULT_SCHEME else ''))
    config.append('        </styles>')
    # One slot per segment; the slot id is the segment number plus one.
    config.append('        <data>')
    for s, default in enumerate(DEFAULT_DATA):
        config.append('            <complication id="%d">' % (s + 1))
        for const, _, _ in DATA:
            config.append('                <type%s>Complications.%s</type>'
                          % (' default="true"' if const == default else '', const))
        config.append('            </complication>')
    config.append('        </data>')
    config += colour_list('dataColors', DEFAULT_DATA_COLOUR)
    config += colour_list('accentColors', DEFAULT_ACCENT_COLOUR)
    config += ['    </watchface-config>', '</resources>']

    icons = [-1] * (max(types.values()) + 1)
    for const, number, icon in DATA:
        icons[number] = 'Icons.' + icon
    code = CHOICES.format(
        icons=', '.join(map(str, icons)),
        default_data='\n'.join('        Complications.%s,' % d for d in DEFAULT_DATA),
        schemes='\n'.join('        %s,  // %d %s' % ('[' + ', '.join('0x%06X' % c for c in cs) + ']' if cs else 'null',
                                                    id_, name) for id_, name, cs in [(0, '(unused)', None)] + SCHEMES),
        default_scheme=DEFAULT_SCHEME, default_data_colour=DEFAULT_DATA_COLOUR,
        default_accent_colour=DEFAULT_ACCENT_COLOUR)

    os.makedirs(os.path.join(root, 'resources', 'configs'), exist_ok=True)
    for path, text in (('resources/strings/choices.xml', '\n'.join(strings) + '\n'),
                       ('resources/configs/watchface.xml', '\n'.join(config) + '\n'),
                       ('source/Choices.mc', code)):
        with open(os.path.join(root, path), 'w') as f:
            f.write(text)


if __name__ == '__main__':
    main()
