#!/usr/bin/env python3
"""Generate source/RingOffsets.mc: whole-pixel offsets for the ring's 78 dots.

The ideal dot centres fall between pixels, and rounding each one on its own leaves
the gaps between neighbours anywhere from 7.6 to 9.2 px instead of 8.5. This picks
every segment's 13 pixels together (Viterbi over the nearby pixels of each dot),
trading a little accuracy in each dot's angle for even gaps and an even distance
from the edge of the display.

    python3 tools/make_ring.py      # writes source/RingOffsets.mc
"""
import math
import os

RADIUS = 122
SEGMENTS = 6
DOTS = 13
DOT_STEP = 4
SEGMENT_STEP = 60

# Cost weights: distance off the circle, gap error between neighbours, and drift
# from the ideal centre (small, only to keep dots near their angle).
RADIAL_WEIGHT = 1.0
GAP_WEIGHT = 1.0
DRIFT_WEIGHT = 0.05
MAX_RADIAL = 0.6
MAX_DRIFT = 1.5


def segment(s):
    gap = 2 * RADIUS * math.sin(math.radians(DOT_STEP / 2))
    cands = []
    for d in range(DOTS):
        a = math.radians(s * SEGMENT_STEP - (DOTS - 1) // 2 * DOT_STEP + d * DOT_STEP)
        fx, fy = RADIUS * math.sin(a), RADIUS * math.cos(a)
        cs = []
        for x in range(math.floor(fx) - 1, math.ceil(fx) + 2):
            for y in range(math.floor(fy) - 1, math.ceil(fy) + 2):
                radial, drift = math.hypot(x, y) - RADIUS, math.dist((x, y), (fx, fy))
                if abs(radial) < MAX_RADIAL and drift < MAX_DRIFT:
                    cs.append((x, y, RADIAL_WEIGHT * radial ** 2 + DRIFT_WEIGHT * drift ** 2))
        cands.append(cs)

    cost = [[c[2] for c in cands[0]]]
    back = [None]
    for d in range(1, DOTS):
        row, br = [], []
        for x, y, own in cands[d]:
            v, j = min((cost[-1][j] + GAP_WEIGHT * (math.dist((x, y), p[:2]) - gap) ** 2, j)
                       for j, p in enumerate(cands[d - 1]))
            row.append(v + own)
            br.append(j)
        cost.append(row)
        back.append(br)

    j = min(range(len(cost[-1])), key=lambda k: cost[-1][k])
    path = []
    for d in range(DOTS - 1, -1, -1):
        path.append(cands[d][j][:2])
        if d > 0:
            j = back[d][j]
    return path[::-1]


TEMPLATE = """// Generated by tools/make_ring.py: change the ring geometry there, then regenerate.
import Toybox.Lang;

module RingOffsets {{

    // Each ring dot's centre relative to the display centre, as a flat
    // [x0, y0, x1, y1, ...] array with y up: segment by segment, each segment's
    // dots in clockwise order.
    const OFFSETS = [
{rows}
    ] as Array<Number>;
}}
"""


def main():
    root = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..')
    rows = []
    for s in range(SEGMENTS):
        pts = segment(s)
        rows.append('        ' + ', '.join('%d, %d' % p for p in pts) + ',')
    with open(os.path.join(root, 'source', 'RingOffsets.mc'), 'w') as f:
        f.write(TEMPLATE.format(rows='\n'.join(rows)))


if __name__ == '__main__':
    main()
