// Generated by tools/make_settings.py: edit the lists there, then regenerate.
import Toybox.Complications;
import Toybox.Lang;

// What the watch face editor offers, and the defaults for anything not yet chosen.
module Choices {

    // Icons number for each complication type a segment can show, indexed by type;
    // -1 for types that are not offered.
    const ICONS = [-1, Icons.BATTERY, Icons.FOOTPRINTS, -1, Icons.STAIRS, Icons.STOPWATCH, -1, -1, -1, -1, -1, -1, -1, -1, Icons.SUNRISE, -1, -1, -1, Icons.HEART, -1, -1, Icons.GAUGE, Icons.STRESS, Icons.BOLT, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, Icons.DROP, -1, Icons.SUN, -1, -1, -1, -1, Icons.MOON] as Array<Number>;

    // Each segment's default complication type, clockwise from the top.
    const DEFAULT_DATA = [
        Complications.COMPLICATION_TYPE_BATTERY,
        Complications.COMPLICATION_TYPE_HEART_RATE,
        Complications.COMPLICATION_TYPE_STEPS,
        Complications.COMPLICATION_TYPE_SOLAR_INPUT,
        Complications.COMPLICATION_TYPE_BODY_BATTERY,
        Complications.COMPLICATION_TYPE_RECOVERY_TIME,
    ] as Array<Number>;

    // Colour schemes by style id: six colours clockwise from the top, or null for
    // Single colour, which uses the Data colour throughout.
    const SCHEMES = [
        null,  // 0 (unused)
        [0x00FF55, 0xFF0055, 0x00AAFF, 0xFFAA00, 0xAA55FF, 0xFFFF00],  // 1 Rainbow
        [0xFFFF00, 0xFFAA00, 0xFF5500, 0xFF0000, 0xFF0055, 0xFF55AA],  // 2 Warm
        [0x00FFFF, 0x00AAFF, 0x0055FF, 0x5555FF, 0xAA55FF, 0x00FFAA],  // 3 Cool
        [0xAAFFAA, 0xFFAAAA, 0xAAFFFF, 0xFFFFAA, 0xFFAAFF, 0xAAAAFF],  // 4 Pastel
        null,  // 5 Single colour
    ] as Array<Array<Number>?>;

    const DEFAULT_SCHEME = 1;
    const DEFAULT_DATA_COLOUR = 0x00FF55;
    const DEFAULT_ACCENT_COLOUR = 0xFFFFFF;
}
